"""
rules/seed_rules.py
────────────────────────
The full ArthaChakra rule book — 56 rules, built from scratch for this
project. All 56 are MANDATORY (category="MANDATORY").

EVAL_STATUS:
  EVALUABLE          - dispatched to a real handler in rules/engine.py
  ADVISORY           - static reminder, no real handler logic
  NOT_YET_EVALUABLE  - underlying data source does not exist yet

STEP 7 UPDATE: S-21, S-22, S-23, S-24, M-09, ES-09 (corporate events) and
S-25, M-11, M-12 (market intel) moved from NOT_YET_EVALUABLE to EVALUABLE.

S-27 added post-Step-7, found via real live TCS data: S-21/S-24/M-09 all
use narrow day-windows before results, but a position entered earlier in
the month stays open until expiry and is still exposed if results land
before that expiry. S-27 is a whole-series block, not a timing window.

PROJECT PATH:  rules/seed_rules.py
"""

from __future__ import annotations

RULE_BOOK: list[dict] = [
    {
        "rule_id": "S-01",
        "name": "India VIX Hard Limit",
        "description": "Never enter when India VIX >= 25",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "vix_hard_limit",
        "notes": "",
    },
    {
        "rule_id": "S-02",
        "name": "VIX Slope / Rising VIX Caution",
        "description": "VIX 20-25 with 5-day rise >3pts = caution zone",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "vix_slope",
        "notes": "",
    },
    {
        "rule_id": "S-03",
        "name": "No Results/Earnings During Series",
        "description": "Skip stock if results scheduled during series",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "CALENDAR",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs corporate_events_cache populated - empty until Step 7",
        "handler": "no_results_during_series",
        "notes": "overlaps with new S-21",
    },
    {
        "rule_id": "S-04",
        "name": "No Corporate Actions During Series",
        "description": "Skip if buyback/split/bonus/rights/dividend scheduled",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "CALENDAR",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs corporate_events_cache populated - empty until Step 7",
        "handler": "no_corporate_actions_during_series",
        "notes": "overlaps with new S-22/S-23",
    },
    {
        "rule_id": "S-05",
        "name": "No Macro Events During Series",
        "description": "Skip entry during Budget/RBI/Fed/Election week",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "CALENDAR",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs macro/economic calendar - not built yet",
        "handler": "no_macro_events_during_series",
        "notes": "",
    },
    {
        "rule_id": "S-06",
        "name": "Range-Bound Stock Confirmation",
        "description": "Only trade stocks range-bound on 3-month chart",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "QUALITATIVE",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "range_bound_check",
        "notes": "manual judgment call - hard to automate",
    },
    {
        "rule_id": "S-07",
        "name": "Stock Beta < 1.2",
        "description": "Only trade stocks with beta < 1.2 vs Nifty",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "beta_check",
        "notes": "",
    },
    {
        "rule_id": "S-08",
        "name": "IV Rank > 40 at Entry",
        "description": "Only sell premium when IVR > 40",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "iv_rank_check",
        "notes": "",
    },
    {
        "rule_id": "S-09",
        "name": "High Liquidity - Bid-Ask Spread",
        "description": "Bid-ask spread < 2% of premium AND OI > 50000",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs bid-ask spread + OI data - not captured in current position model",
        "handler": "liquidity_check",
        "notes": "",
    },
    {
        "rule_id": "S-12",
        "name": "Primary Entry Timing: First Wednesday, Not Before 12 PM",
        "description": "Entry permitted from first Wednesday of new series onward , not before 12 PM that day. No upper time bound - enter whenever margin/conditions are right after this point.",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "OPTIONAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "entry_timing_window",
        "notes": "was \"First Friday 12PM\"  corrected to First Wednesday; removed the narrow window",
    },
    {
        "rule_id": "S-14",
        "name": "Delta Neutrality at Entry",
        "description": "Net delta (PE-CE) within +/-0.05 at entry",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "delta_neutral_at_entry",
        "notes": "",
    },
    {
        "rule_id": "S-15",
        "name": "High-IV Entry Protocol",
        "description": "VIX 20-25 use 12-13% range + protective put",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "high_iv_entry_protocol",
        "notes": "",
    },
    {
        "rule_id": "S-26",
        "name": "Strike Distance Scales with Week of Series",
        "description": "OTM% required decreases 2% per week as series progresses. Week boundaries are 7-calendar-day blocks starting (previous expiry + 1 day); expiry = last Tuesday of month. 4-week series: W1=10% W2=8% W3=6% W4=4%. 5-week series: W1=12% W2=10% W3=8% W4=6% W5=4%. Example (Jun, 5-week): W1=27May-2Jun(12%) W2=3-9Jun(10%) W3=10-16Jun(8%) W4=17-23Jun(6%) W5=24-30Jun(4%).",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "strike_distance_schedule",
        "notes": "REPLACES S-10/S-11. Also drives A-08 re-entry calc (see below). Week count (4 vs 5) determined by calendar days between consecutive expiries: 28 days=4wk 35 days=5wk.",
    },
    {
        "rule_id": "EP-01",
        "name": "Tiered Leg Closure: Premium Decay Threshold Scales with Week",
        "description": "PER-LEG trigger (not whole-position): when a leg's current premium has decayed to (100% minus the week's threshold) of its entry premium, close the ENTIRE quantity on that leg (e.g. 10 lots sold at Rs5, 50% threshold -> close all 10 lots when premium hits Rs2.5). 4-week series: W1=50% W2=60% W3=70% W4=80% (through Thursday). 5-week series: W1=50% W2=60% W3=70% W4=75% W5=80% (through Thursday). Final 3 trading days before expiry (Friday/Monday/Tuesday-expiry) override the week value regardless of 4 or 5-week series: Friday=85% Monday=90% Tuesday(expiry)=95%. After closing the leg, sell a new leg on that same side per A-02's rebalancing mechanic.",
        "category": "MANDATORY",
        "group": "Exit-Profit",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "tiered_leg_closure",
        "notes": "UPDATED - per-leg not whole-position. REPLACES old EP-01. Hands off to A-02 for the rebalancing leg sale - do not duplicate that logic here.",
    },
    {
        "rule_id": "EP-02",
        "name": "Final Exit: Last Friday/Monday of Series Post 2 PM",
        "description": "Close ALL remaining open positions by last Friday or Monday of the expiry series (before expiry Tuesday), after 2PM.",
        "category": "MANDATORY",
        "group": "Exit-Profit",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "CALENDAR",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "final_exit_window",
        "notes": "UPDATED - was \"Last Tuesday/Wednesday\"  corrected to Friday/Monday since expiry itself is Tuesday",
    },
    {
        "rule_id": "EP-04",
        "name": "Emergency Exit VIX Spike Post-Entry",
        "description": "Exit all if VIX rises >5pts in one session",
        "category": "MANDATORY",
        "group": "Exit-Profit",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "vix_spike_exit",
        "notes": "",
    },
    {
        "rule_id": "EP-05",
        "name": "Exit on Post-Entry Corporate Event",
        "description": "Exit immediately if event announced after entry",
        "category": "MANDATORY",
        "group": "Exit-Profit",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "LOOKUP",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs corporate_events_cache populated - empty until Step 7",
        "handler": "post_entry_event_exit",
        "notes": "overlaps with new ES-09",
    },
    {
        "rule_id": "ES-01",
        "name": "Range Breach: Close the Breached Leg",
        "description": "At entry, the strangle's two strikes (PE and CE) define a range - roughly 10% on either side of spot. If the stock price moves beyond either strike during the session, that side's leg is breached: close ONLY that leg (PE if breached downward, CE if breached upward), not the entire strangle.",
        "category": "MANDATORY",
        "group": "Exit-StopLoss",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "range_breach",
        "notes": "CLARIFIED wording - confirmed single-leg action  not whole-strangle. Unchanged in substance from original.",
    },
    {
        "rule_id": "ES-04",
        "name": "Individual Leg Delta SL Delta>0.30",
        "description": "Flag leg for review if its delta exceeds 0.30 - WARNING ONLY  not an automatic exit. Trader decides whether to close.",
        "category": "MANDATORY",
        "group": "Exit-StopLoss",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "leg_delta_warning",
        "notes": " now warning-only per your correction UPDATED - was an automatic close trigger",
    },
    {
        "rule_id": "ES-10",
        "name": "Ratio-Breach Exit: Cannot Rebalance Even at 3:1 Cap",
        "description": "If the position is already at the 3:1 CE:PE ratio cap (A-10) and delta still cannot be brought back to neutral by selling further legs (since doing so would breach the cap), this is the real stop-loss trigger - exit rather than keep trying to add legs you are no longer allowed to add.",
        "category": "MANDATORY",
        "group": "Exit-StopLoss",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "ratio_breach_exit",
        "notes": "NEW - replaces money-based SL concept entirely. OPEN QUESTION NOT YET ANSWERED: does this exit the ENTIRE strangle  or only close down the excess legs on the stuck side? Confirm before this goes into the engine - placeholder scope assumed as \"entire position\" pending your confirmation.",
    },
    {
        "rule_id": "ES-11",
        "name": "Capping Hedge as Alternative to ES-10 Exit",
        "description": "At ES-10's trigger point (position maxed at A-10's 3:1 ratio cap, delta still not neutral), the trader has a second option besides exiting: buy ONE protective long option further OTM than the existing short legs on the stuck side (e.g. stuck at 3 short CE legs - buy a further-OTM long call). This hedge does NOT count against the leg-count limit (same precedent as L-06 - protective hedges sit outside leg caps), so it doesn't breach A-10. Its purpose is to cap further loss on that side while keeping the position open, as an alternative to crystallizing the loss immediately via ES-10's exit. Choosing exit vs. hedge at this fork is a discretionary judgment call (days left in series, hedge cost relative to risk already exposed, current IV) - this rule does not mandate one over the other, it formalizes (b) as a defined available action.",
        "category": "MANDATORY",
        "group": "Exit-StopLoss",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "capping_hedge_alternative",
        "notes": "NEW - the hedging option discussed alongside A-11. Only applies once ES-10 has already triggered; does not change ES-10 itself",
    },
    {
        "rule_id": "A-02",
        "name": "Roll Adjustment: Resell at Week-Aware OTM%",
        "description": "Not an independent trigger - this is the rebalancing action that executes once EP-01's week-scaled premium-decay threshold has closed a leg. Sells the replacement leg at the OTM% level from S-26's weekly schedule, measured from CURRENT spot (same lookup as A-08).",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "rebalance_action_reminder",
        "notes": "REWORDED - removed standalone \"30% of WAP\" trigger; closing now happens entirely via EP-01's logic",
    },
    {
        "rule_id": "A-03",
        "name": "Threatening Leg Early Delta Trigger 0.25",
        "description": "Proactively adjust an at-risk leg when its delta crosses 0.25 - this is the early/middle step between normal operation and A-10's 3:1 ratio cap. Without it, delta drift only gets corrected reactively (via EP-01's profit trigger or hitting the ratio cap).",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "early_delta_trigger",
        "notes": "RECOMMENDATION: keep - fills the gap between \"fine\" and \"maxed out at 3:1.\" Final call is yours.",
    },
    {
        "rule_id": "A-05",
        "name": "Delta Neutral After Every Adjustment - Target Not Strict Zero",
        "description": "Recheck delta balance after every roll/adjustment and aim as close to zero as practical. Not a strict zero requirement - if reaching exact zero would require selling a leg too deep ITM to be practical, a small residual skew is acceptable. Whenever an adjustment happens, the new leg's strike must explicitly follow A-08's re-entry rule (week-aware OTM% from current spot) - this link is required, not assumed.",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "delta_neutral_after_adjustment",
        "notes": "REWORDED - softened from strict zero to \"as close as practical\"; made the A-08 link explicit rather than implicit",
    },
    {
        "rule_id": "A-06",
        "name": "No Adjustment if Range Below Week-Scaled Threshold",
        "description": "Do not adjust if the range to the threatening strike is below the threshold for the CURRENT week of the series (not a flat 4%) - what counts as 'threatened' in week 1-3 is different from week 4-5, since less time remains for the stock to move that far.",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Per-week threshold VALUES were never finalized during rule review - need user input, not a missing data source",
        "handler": "adjustment_range_threshold",
        "notes": "UPDATED - flat 4% replaced with a week-scaled threshold",
    },
    {
        "rule_id": "A-07",
        "name": "No New Short Positions Final 3 Sessions",
        "description": "No new shorts in the last 3 trading days before expiry (was 5). At that point, adding a new short leg wouldn't meaningfully move delta given how little time remains - freeing that margin earlier instead, so it can be deployed toward next month's series rather than sitting idle.",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "CALENDAR",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "no_new_shorts_final_sessions",
        "notes": "UPDATED - window shortened from 5 to 3 sessions",
    },
    {
        "rule_id": "A-08",
        "name": "Re-entry Strike: Week-Aware OTM% from Current Spot",
        "description": "When re-entering after closing/adjusting a leg, required OTM% is looked up from S-26's weekly schedule using TODAY's date (not the original entry spot) - NOT a flat 10%. E.g. re-entering in week 3 of a 4-week series requires only 6% OTM from current spot, not 10%.",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "reentry_strike_otm",
        "notes": "CONFIRMED - unchanged from last round",
    },
    {
        "rule_id": "A-10",
        "name": "Maximum CE:PE Leg Ratio 3:1",
        "description": "No fixed count limit on adjustments per leg. The governing constraint is delta neutrality, enforced structurally as a leg-count ratio: number of CE legs relative to PE legs (or vice versa) must never exceed 3:1, checked against CURRENTLY OPEN legs only (not adjustment history). E.g. with 1 PE leg open, max 3 CE legs allowed total; same cap in reverse. Works alongside A-05 (delta check after every adjustment) and L-02/L-03 (total leg count caps).",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "max_ce_pe_ratio",
        "notes": "REPLACES A-01. Check this ratio BEFORE selling any new leg via A-02 or A-03 - if a new leg would breach 3:1  block the sale and force a different action (e.g. close more of the other side instead).",
    },
    {
        "rule_id": "A-11",
        "name": "Naked Position Exception: CE-Side Only in Final Week",
        "description": "Going naked (one side of the strangle closed, leaving only a single leg open with no counter-leg) is an EXCEPTION, not standard practice - typically arises when the PE leg is closed on booked profit, leaving the CE leg open alone. HARD GATE (must be true): only acceptable in the LAST WEEK of the series - theta/delta by then are too low to justify selling a fresh counter-leg just to restore balance. Naked CE is tolerated; naked PE is not preferred, since the market can drop fast but doesn't rise as fast - PE-side risk moves faster. Secondary confirming factors (reinforce the decision, not independently mandatory): the remaining leg should ideally be comfortably OTM (~5%+, low odds of breach in the time left). If the hard gate (last week) isn't met, do not go naked - close out or re-strangle instead.",
        "category": "MANDATORY",
        "group": "Adjustment",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "naked_position_exception",
        "notes": "NEW - fills the hedging/naked-position gap identified from the June trade book (MARUTI/ITC/POWERGRID/Marico all went naked mid-series",
    },
    {
        "rule_id": "C-01",
        "name": "Single Stock Cap: HARD 15% of Total Margin - Continuous Check",
        "description": "No instrument's COMBINED STRANGLE margin (all legs together - both original PE/CE and any extra legs added through rebalancing) may exceed 15% of TOTAL MARGIN. This is a HARD cap, checked CONTINUOUSLY - at setup, re-entry, and every adjustment - not just once at initial entry. Block any new leg or adjustment that would push the combined margin past 15%.",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs account-level margin aggregation across all open strangles - not built yet",
        "handler": "single_stock_margin_cap",
        "notes": "UPDATED - was 20% of option fund checked once at entry; now 15% of total margin",
    },
    {
        "rule_id": "C-02",
        "name": "Always Maintain 10% Margin Buffer",
        "description": "Keep cash/liquid >=10% of deployed margin",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs total account margin/funds figure - not fetched anywhere yet",
        "handler": "margin_buffer_check",
        "notes": "",
    },
    {
        "rule_id": "C-03",
        "name": "Minimum 6 Instruments Diversification",
        "description": "Always hold at least 6 different instruments - raised from 4 so 85% total deployment (C-04) is mathematically reachable without breaching the new 15% single-stock cap (C-01).",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs aggregation across all open positions for one user - not built yet",
        "handler": "min_instruments_check",
        "notes": "UPDATED - was minimum 4",
    },
    {
        "rule_id": "C-04",
        "name": "Total Deployed <=85% of Total Margin",
        "description": "Total margin deployed across all positions never exceeds 85% of TOTAL MARGIN (was option fund - now matches C-01's denominator).",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs total account margin/funds figure - not fetched anywhere yet",
        "handler": "total_deployed_check",
        "notes": "UPDATED - denominator changed from \"option fund\" to \"total margin\" for consistency with C-01",
    },
    {
        "rule_id": "C-05",
        "name": "Performance-Based Reallocation Each Series",
        "description": "Rebalance capital +/-25% based on last series returns",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "reallocation_reminder",
        "notes": "personal portfolio-management habit",
    },
    {
        "rule_id": "C-06",
        "name": "Index Options Max 40% of Combined Portfolio",
        "description": "Index options <=40% of combined margin",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "THRESHOLD",
        "eval_status": "NOT_YET_EVALUABLE",
        "not_evaluable_reason": "Needs aggregation across all open positions for one user - not built yet",
        "handler": "index_options_cap",
        "notes": "",
    },
    {
        "rule_id": "C-07",
        "name": "New Instrument Half-Size First Series",
        "description": "New instruments get 50% of target allocation first series",
        "category": "MANDATORY",
        "group": "Capital",
        "default_on": True,
        "severity": "LOW",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "new_instrument_half_size_reminder",
        "notes": "personal onboarding habit",
    },
    {
        "rule_id": "L-01",
        "name": "Original Strangle Exactly 2 Short Legs",
        "description": "Every new strangle = exactly 1 CE + 1 PE at entry",
        "category": "MANDATORY",
        "group": "LegCount",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "exactly_two_legs_at_entry",
        "notes": "KEPT unchanged - confirmed correct",
    },
    {
        "rule_id": "L-03",
        "name": "Leg Count Governed by A-10's 3:1 Ratio - Hard Cap 8",
        "description": "No separate flat leg-count rule - leg count is governed entirely by A-10's 3:1 CE:PE ratio cap. At maximum allowed imbalance (3:1), the hard ceiling is 6 legs on one side + 2 on the other = 8 total, which is the absolute hard cap - emergency close if breached.",
        "category": "MANDATORY",
        "group": "LegCount",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "leg_count_hard_cap",
        "notes": "UPDATED - absorbed L-02's \"normal max\" concept; the number 8 now derives directly from A-10's ratio rather than standing as its own independent limit",
    },
    {
        "rule_id": "L-05",
        "name": "Both Legs Same Expiry Series Only",
        "description": "CE and PE must be from same expiry date",
        "category": "MANDATORY",
        "group": "LegCount",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "same_expiry_check",
        "notes": "KEPT unchanged - confirmed correct",
    },
    {
        "rule_id": "L-06",
        "name": "Protective Hedge Not Counted in Leg Limit",
        "description": "Long protective options excluded from leg count",
        "category": "MANDATORY",
        "group": "LegCount",
        "default_on": True,
        "severity": "LOW",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "hedge_not_counted_reminder",
        "notes": "KEPT unchanged - confirmed correct (currently dormant since hedges aren't in use)",
    },
    {
        "rule_id": "X-02",
        "name": "GTT Orders Within 2 Hours of Entry",
        "description": "Set GTT stop-loss order within 2 hours of every entry (was 24 hours)",
        "category": "MANDATORY",
        "group": "Operational",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "gtt_order_reminder",
        "notes": "UPDATED - window shortened from 24 hours to 2 hours",
    },
    {
        "rule_id": "X-03",
        "name": "Price + Breach Alerts: 4 Per Strangle",
        "description": "Set 4 alerts per strangle: Alert 1 = CE leg at 50% (price alert), Alert 2 = PE leg at 50% (price alert), plus 2 breach alerts (CE strike breach, PE strike breach).",
        "category": "MANDATORY",
        "group": "Operational",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "alert_setup_reminder",
        "notes": "UPDATED - was a single generic \"price alert",
    },
    {
        "rule_id": "X-09",
        "name": "Next-Series Allocation Plan: First Day After Last Expiry",
        "description": "Complete next series allocation plan by the first calendar day after the previous expiry. Example: June 2026 expires 30 June, so the plan is due 1 July.",
        "category": "MANDATORY",
        "group": "Operational",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "allocation_plan_reminder",
        "notes": "UPDATED - anchor confirmed as 1st day after expiry (not Wednesday-after as previously drafted - corrected per your clarification)",
    },
    {
        "rule_id": "X-10",
        "name": "Trade Record Same-Day Entry",
        "description": "Record every trade in daily sheet same day",
        "category": "MANDATORY",
        "group": "Operational",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "trade_record_reminder",
        "notes": "KEPT unchanged",
    },
    {
        "rule_id": "X-12",
        "name": "Series Start Checklist: Learn From Last Month + Revised Checklist",
        "description": "Run a full series-start checklist before the first trade of a new series. Before running it, review the PREVIOUS month's outcomes/violations and incorporate any lessons into a revised checklist for the new series - not just a static repeat of the same checklist every time.",
        "category": "MANDATORY",
        "group": "Operational",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "QUALITATIVE",
        "eval_status": "ADVISORY",
        "not_evaluable_reason": "",
        "handler": "series_checklist_reminder",
        "notes": "UPDATED - added the \"learn from last month",
    },
    {
        "rule_id": "RF-02",
        "name": "Any ITM Short Option Held Overnight",
        "description": "Never hold an ITM short option overnight",
        "category": "MANDATORY",
        "group": "RedFlag",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "THRESHOLD",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "itm_overnight",
        "notes": "KEPT - no conflict. Overlaps with ES-01 (which fires intraday on breach) but RF-02 is the overnight backstop in case ES-01 somehow didn't fire same-day. Different timing",
    },
    {
        "rule_id": "S-21",
        "name": "No Entry Within 5 Days of Results",
        "description": "Block entry if results within 5 trading days",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "no_entry_near_results",
        "notes": "KEPT - no conflict. Overlaps with S-03's broader \"skip whole stock if results scheduled during series\" but adds a precise 5-day window; complementary",
    },
    {
        "rule_id": "S-22",
        "name": "Block Entry on M&A/Merger Announced",
        "description": "Block entry if merger/demerger announced",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "no_entry_on_merger",
        "notes": "KEPT - no conflict. S-04's corporate-action list (buyback/split/bonus/rights/dividend) doesn't actually include merger/demerger - this fills a real gap",
    },
    {
        "rule_id": "S-23",
        "name": "No Entry Within 3 Days of Split/Bonus Ex-Date",
        "description": "Block entry within 3 days of split/bonus ex-date",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "no_entry_near_split_bonus",
        "notes": "KEPT - no conflict. Overlaps with S-04's blanket \"skip during series\" for the same event type",
    },
    {
        "rule_id": "S-24",
        "name": "Reduce Size 50% in Results Week",
        "description": "Halve lot size if results are 6-7 days away",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "reduce_size_results_week",
        "notes": "KEPT - no conflict. Sequences cleanly with S-21: 6-7 days out = reduce size",
    },
    {
        "rule_id": "M-09",
        "name": "Monitor Board Meeting/AGM Within 7 Days",
        "description": "Flag for review if board meeting/AGM within 7 days",
        "category": "MANDATORY",
        "group": "Monitoring",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "monitor_board_meeting",
        "notes": "KEPT - no conflict. Informational only",
    },
    {
        "rule_id": "ES-09",
        "name": "Exit Open Position on Same-Day Merger",
        "description": "Exit immediately if merger/demerger announced same day",
        "category": "MANDATORY",
        "group": "Exit-StopLoss",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "exit_on_same_day_merger",
        "notes": "KEPT - no conflict. The original ES-06 naming collision is moot now since old ES-06 (re-entry cooling) was deleted entirely today. This is a real event-driven exit",
    },
    {
        "rule_id": "S-25",
        "name": "Block Entry on 3+ Bearish Brokerage Calls",
        "description": "Block entry if 3+ distinct bearish broker calls in 7 days",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "HIGH",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "block_on_bearish_calls",
        "notes": "KEPT - no conflict.",
    },
    {
        "rule_id": "M-11",
        "name": "Warn on Any Bearish Signal",
        "description": "Warn before entry if any bearish signal found",
        "category": "MANDATORY",
        "group": "Monitoring",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "warn_bearish_signal",
        "notes": "KEPT - no conflict. Sequences cleanly with S-25: any signal = warn",
    },
    {
        "rule_id": "M-12",
        "name": "Review All Positions on Sector-Wide Bearish News",
        "description": "Flag portfolio review if sector-wide bearish news detected",
        "category": "MANDATORY",
        "group": "Monitoring",
        "default_on": True,
        "severity": "MEDIUM",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "review_sector_bearish_news",
        "notes": "KEPT - no conflict. Portfolio-level flag",
    },
    {
        "rule_id": "S-27",
        "name": "No Entry If Results Fall Before Monthly Expiry",
        "description": "If a quarterly/annual/half-yearly results announcement for this stock is scheduled at any point between today and the current series expiry (last Tuesday of the month), block entry for this stock for the rest of the series - entering earlier in the month does not avoid the risk, since the position would still be open and exposed when results actually hit. Also applies to re-entries and adjustments mid-series, not just brand-new entries.",
        "category": "MANDATORY",
        "group": "Setup",
        "default_on": True,
        "severity": "CRITICAL",
        "eval_type": "LOOKUP",
        "eval_status": "EVALUABLE",
        "not_evaluable_reason": "",
        "handler": "no_entry_results_before_expiry",
        "notes": "NEW - closes a real gap found via live TCS data. S-21 only blocks the last 5 days before results; S-24 only reduces size 6-7 days before. A position entered earlier in the month (e.g. 10+ days before results) would still be open when results hit, since strangles run to expiry not to the results date. Distinct from S-21 - this is a whole-series block, not a tactical timing window. Applies to re-entry/adjustment too, per explicit confirmation.",
    },
]


def get_rule_book() -> list[dict]:
    """Returns the static rule book. Single source of truth for seeding."""
    return RULE_BOOK